### ISSUE TITLE
Can you confirm if python3.11 is mandatory for using pythonfmu3 

### ISSUE THREAD

**Issue by gricharuk** [StephenSmith25/PythonFMU3#8]
I have built a test application with pythonfmu3, it works fine being instantiated with fmpy, 

But I need to actually run on a second server that has to run python3.9, redhat 8.

When I rebuild - it runs, when I try and instantiate it fails stating it is missing a python3.11 "so" file.

When I grep the folder, and unzip the FMU file, for python3.11 - I can see
```
grep -R "python3.11"
Binary file FMUWrapper.fmu matches
Binary file binaries/x86_64-linux/FMUWrapper.so matches
```

But my python version is 
```
python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

```

These are two different machines so I don't think I have a polluted environment, I've performed a clean etc. On the second machine I don't have python3.11 installed at all.

Any thoughts? is this a hard coded version of python?

**Comment by StephenSmith25** [comment]
The project does not depend on a particular version of python. It uses the stable API, so `python > 3.6ish` should work. The issue is with the CI builds and the upload to pypi. When the CI builds the project and uploads it it occurs within a `3.11` environment. There are similar issues with PythonFMU, for example https://github.com/NTNU-IHB/PythonFMU/issues/128 . 

I think the fastest solution, if you can - is to build the project from source. If you build from source it will use whatever Python install you have in your build environment. Which is primarily achieved with 

1. cd pythonfmu3
/pythonfmu-export
2. build the project, build scripts in the folder can be used
3. now cd into the root and do pip install ., or pip install -e .

Let me know if you need any more advice, or if that will not work for you.  Maybe those instructions are not the best --

As a note, I think if I create a conda version of this project (rather than pip) it should work. But I have not got round to that yet.

**Comment by gricharuk** [comment]
Thanks for the feedback - I will have a try!

I appreciate your work, a really useful library.....

**Comment by StephenSmith25** [comment]
Thanks, let me know if you run into any issues

**Comment by gricharuk** [comment]
Hi, I've rebuilt for python3.9 - it works fine, 

I did a few actions on my machine if you are interested?
- installed python3.9 
- uninstalled python3.11
- used the "alternatives" method to select the default python version.
- Build causes error related to cmake "Could NOT find PythonLibs", the python lib and include were not set correctly so installed python39_devel 
- Rebuild and installed pythonfmu3 as per your instructions.
- built and installed the FMUv3 test FMU and code
- executed simple test with a machine without python3.11: OK
- grep'ed build fmu for python version.
```
[FMIv3]# grep python FMUWrapper.fmu 
Binary file FMUWrapper.fmu matches
[FMIv3]# grep python3.9 FMUWrapper.fmu 
Binary file FMUWrapper.fmu matches
[FMIv3]# grep python3.11 FMUWrapper.fmu 
[FMIv3]#

```
Looks good - I'll leave you to figure out a method to remove the dependency, this solution works for me!
